checkbox:
  - packages/checkbox/**/*
core:
  - packages/core/**/*
hooks:
  - packages/hooks/**/*
react:
  - packages/react/**/*
switch:
  - packages/switch/**/*
docs:
  - docs/**/*
templates:
  - templates/**/*
scripts:
  - scripts/**/*
