name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.4.0]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Restore Next Config
        uses: actions/cache@v2
        with:
          path: ~/.config/nextjs-nodejs/**
          key: ${{ runner.os }}-next-${{ hashFiles('**/yarn.lock') }}

      - name: Restore Turbo Cache
        uses: actions/cache@v2
        with:
          path: |
            **/.turbo/turbo-*.log
            !**/node_modules/**
          key: ${{ runner.os }}-turbo-${{ hashFiles('**/yarn.lock') }}

      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.FLUX_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.FLUX_GPG_PASSPHRASE }}
          git_push_gpgsign: 'true'
          git_commit_gpgsign: true
          git_user_signingkey: true

      - name: Install Dependencies
        run: yarn --immutable

      - name: Run Linter
        run: yarn lint
        env:
          VERCEL_ARTIFACTS_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ARTIFACTS_OWNER: ${{ secrets.VERCEL_OWNER }}
