name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Restore Next Config
        uses: actions/cache@v2
        with:
          path: ~/.config/nextjs-nodejs/**
          key: ${{ runner.os }}-next-${{ hashFiles('**/yarn.lock') }}

      - name: Restore Turbo Cache
        uses: actions/cache@v2
        with:
          path: |
            **/.turbo/turbo-*.log
            !**/node_modules/**
          key: ${{ runner.os }}-turbo-${{ hashFiles('**/yarn.lock') }}

      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.FLUX_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.FLUX_GPG_PASSPHRASE }}
          git_push_gpgsign: true
          git_commit_gpgsign: true
          git_user_signingkey: true

      - name: Set Canary Meta
        uses: actions/github-script@v5
        id: is-canary
        with:
          result-encoding: json
          script: |
            const isCanary = context.ref.includes('canary');
            return {
              isCanary,
              cliffPath: isCanary ? '.github/config/canary-cliff.toml' : '.github/config/cliff.toml'
            };

      - name: Generate Changelog
        uses: orhun/git-cliff-action@v1
        id: git-cliff
        with:
          config: ${{ steps.is-canary.outputs.cliffPath }}
          args: -l
        env:
          OUTPUT: CHANGES.md

      - name: Set Release Body
        id: release
        shell: bash
        run: |
          r=$(cat ${{ steps.git-cliff.outputs.changelog }})
          r="$(printf "$r" | tail -n +3)"
          r="${r//'%'/'%25'}"
          r="${r//$'\n'/'%0A'}"
          r="${r//$'\r'/'%0D'}"
          echo "::set-output name=release_body::$r"

      - name: Install Dependencies
        run: yarn --immutable

      - name: Publish Packages
        run: yarn publish --scope="-@flux-ui/docs"

      - name: Release Version
        uses: softprops/action-gh-release@v1
        with:
          body_path: ./CHANGES.md
          prerelease: ${{ steps.is-canary.outputs.isCanary }}
          discussion_category_name: Releases
          token: ${{ secrets.GITHUB_TOKEN }}
